spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/database?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate.default_schema: blog_db
  flyway:
    enabled: true
    schemas: blog_db
    table: flyway_schema_history

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

server:
  address: 0.0.0.00

cloudinary:
  name: ${CLOUDINARY_NAME}
  key:  ${CLOUDINARY_APIKEY}
  secret: ${CLOUDINARY_SECRET}